### ISSUE TITLE
 Fatal error

### ISSUE THREAD

**Issue by huubl** [mt-support/tec-labs-ce-convert-content-to-blocks#1]
I get a fatal error:

`Uncaught Exception: Error while making community-tickets.main: nothing is bound to the 'community-tickets.main' id and it's not an existing or instantiable class.`

**Comment by andrasguseo** [comment]
Thanks! I'm looking at this.

**Comment by andrasguseo** [comment]
@huubl Can you share more details on how and when you get that fatal?

**Comment by andrasguseo** [comment]
@huubl I think I fixed that issue now. Please try with the current main branch, which is version 2.5.1-dev. Thanks!
